version: "3.9"

services:
  server:
    build: .
    image: flaviogf/star_wars_backend
    restart: always
    environment:
      DATABASE_URL: mongodb://root:calopsita@mongo
    ports:
      - 3000:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: calopsita
