openapi: 3.0.0

info:
  title: Star Wars Backend
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: development

paths:
  /planets:
    post:
      tags:
        - planets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPlanetRequest"
      responses:
        "201":
          description: Created
        "402":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
    get:
      tags:
        - planets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListPlanetResponse"
        "500":
          description: Internal Server Error
  /planets/{id}:
    get:
      tags:
        - planets
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPlanetResponse"
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - planets
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

components:
  schemas:
    AddPlanetRequest:
      type: object
      properties:
        name:
          type: string
        climate:
          type: string
        terrain:
          type: string
    ListPlanetResponse:
      type: array
      items:
        $ref: "#/components/schemas/GetPlanetResponse"
    GetPlanetResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        climate:
          type: string
        terrain:
          type: string
        movies:
          type: number
